<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Malison.Core</RootNamespace>
    <AssemblyTitle>Malison.Core</AssemblyTitle>
    <Product>Malison.Core</Product>
    <Copyright>Copyright ©  2010</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\bin\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Update="System.Core">
      <RequiredTargetFramework>8.0</RequiredTargetFramework>
    </Reference>
    <Reference Update="System.Xml.Linq">
      <RequiredTargetFramework>8.0</RequiredTargetFramework>
    </Reference>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bramble.Core\Bramble.Core.csproj" />
  </ItemGroup>
</Project>