<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SDL3-CS" Version="3.4.14" />
    <PackageReference Include="SDL3-CS.Linux" Version="3.4.14" />
    <PackageReference Include="SDL3-CS.Windows" Version="3.4.14" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Bramble.Core">
      <HintPath>..\External\Bramble.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Myrmidon.Core\Myrmidon.Core.csproj" />
  </ItemGroup>

</Project>
